### ISSUE TITLE
Stops working after "cb tab clicked"

### ISSUE THREAD

**Issue by OniToibas** [SnoopLawg/PyAutoRaid#3]
First error that comes is almost immidiately when running Main.exe:
![image](https://user-images.githubusercontent.com/131984315/234892317-88f4d4a2-0bd6-4180-9335-b819741f1b6f.png)

Second error that comes is:
![image](https://user-images.githubusercontent.com/131984315/234892454-7d41ada1-729b-4c9e-a139-79dba17be42b.png)

I have tried setting the amount of keys to run in Clan boss tab, however after clicking Submit and restarting Main.exe, it has not saved.

**Comment by SnoopLawg** [comment]
> I have tried setting the amount of keys to run in Clan boss tab, however after clicking Submit and restarting Main.exe, it has not saved.
Try to hit the calculate button. Should fix the saving. I will change it to say like save rather than calculate on next release.

> no such table PyAutoRaid_Configure
This happens on first run but shouldnt happen on the second one. I will fix this too, but is it still happening after the first run?

>CBx,CBy type error
This happens when it saw the image and tried to click it but didnt see it anymore. It could have been covered up, closed or in most cases, my code just doesnt wait long enough after "seeing" it to try to click it. Has this happened more than once? good to know I can edit that now too :)

**Comment by OniToibas** [comment]
> I have tried setting the amount of keys to run in Clan boss tab, however after clicking Submit and restarting Main.exe, it has not saved.

I've tried the calculate button, I get the same issue.
Calculate without pressing Submit
Calculate and pressing Submit after
Submit and then pressing Calculate

> no such table PyAutoRaid_Configure
Yes, it happens every time I try and start PyAutoRaid and when Raid launches,

> CBx,CBy type error

Yes, it has happened more than once

However, I just tried filling in amount of runs in CB (without ticking the checkboxes) and hitting Calculate, now it actually proceeded doing CB, the difference was I didn't check any of the boxes. It went for Nightmare which is correct for the account I'm currently doing it on.

**Comment by SnoopLawg** [comment]
>I have tried setting the amount of keys to run in Clan boss tab, however after clicking Submit and restarting Main.exe, it has not saved.

I seem to have fixed it with the new release. Let me know if it worked. I added more text to explain and the button to "Set number of battles" with a more descriptive warning sign

>no such table PyAutoRaid_Configure

I made a temporary fix that does what you did and downloads the Github Settings on creation. Again try with the newest release 1.6 and let me know. 

>CBx,CBy type error

This should be fixed with checkboxes gone now in the gui?

**Comment by OniToibas** [comment]
Yea it now behaves differently, there still seems to be some kind of issue for the Main window to write to the Settings.db, if I change to run 2 nightmare and 1 brutal, it doesn't save after clicking "Set number of fights" and then Submit, it still tries to run Ultra Nightmare 4 times and then nightmare 2 times, if I relaunch Main.exe, the old settings with UNM 4 and NM 2 is still there.

Just wanted to also say I really like the idea of this tool.

**Comment by SnoopLawg** [comment]
Just fixed it (pretty sure lol) on two of my computers. It now should be fixed. Expect when you download version 1.7 that it will now start and create a fresh Settings.db file (if one does not exist.) and a log.txt file too. Let me know if that works now for ya.

I am very interested on using this on virtual machines too but am unsure if it works? Would this program still work if you minimize the virtual machine? if so that would be huge and I could then have it download raid etc. and run without needing a monitor take it over in a way...
